name: plantdetection
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  curved_navigation_bar:
  font_awesome_flutter:
  flutter_svg:
  camera:
  image_picker:
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_messaging:
  cloud_firestore:
  fluttertoast:
  firebase_database:
  #for Current Date
  intl:
  lottie:
  page_transition:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
